import {Images} from '../Config';

export const amenityIcons = {
  'Air conditioning': Images.AC,
  Lobby: Images.LOBBY,
  '24-hour reception': Images.RECEPTION,
  '24-hour check-in': Images.CHECKIN_24HR,
  'Hotel Safe': Images.SAFE,
  'Currency Exchange': Images.CURRENCY_EXCHANGE,
  Cloakroom: Images.CLOAKROOM,
  Foyer: Images.FOYER,
  Lifts: Images.LIFTS,
  Café: Images.CAFE,
  'Newspaper kiosk': Images.NEWSPAPER_KIOSK,
  'Small supermarket': Images.SMALL_SUPERMARKET,
  Shops: Images.SHOPS,
  Hairdresser: Images.HAIRDRESSER,
  'Bar(s)': Images.BARS,
  'Pub(s)': Images.PUB,
  Nightclub: Images.NIGHTCLUB,
  Theatre: Images.THEATRE,
  Casino: Images.CASINO,
  'Games room': Images.GAMES_ROOM,
  'Restaurant(s)': Images.RESTAURANT,
  'Restaurant(s) with air conditioning': Images.RESTRO_WITH_AC,
  'Restaurant(s) with non-smoking area': Images.RESTRO_NON_SMOKING_AC,
  'Restaurant(s) with high-chairs': Images.RESTAURANT_HIGH_CHAIRS,
  'Conference Room': Images.CONFERENCE_ROOM,
  'Mobile Phone Network': Images.MOBILE_NETWORK,
  'Internet access': Images.INTERNET_ACCESS,
  'WLAN access': Images.WLAN_ACCESS,
  'Room Service': Images.ROOM_SERVICE,
  'Laundry Service': Images.LAUNDRY_SERVICE,
  'Medical Assistance': Images.MEDICAL_ASSISTANCE,
  'Bicycle Cellar': Images.BICYCLE_CELLAR,
  'Bicycle Hire': Images.BICYCLE_CELLAR,
  'Car Park': Images.CARS_ACTIVE,
  Garage: Images.GARAGE,
  'Kids Club': Images.KIDS_CLUB,
  Playground: Images.PLAYGROUND,
  'TV Room': Images.TV_ROOM,
  'Laundry Facilities': Images.LAUNDRY_SERVICE,
  Pets: Images.PETS,
  Waterslide: Images.WATERSLIDE,
  'Disability-friendly': Images.DISABILITY_FRIENDLY,
  Bathroom: Images.BATHROOM,
  Shower: Images.SHOWER,
  Bathtub: Images.BATHTUB,
  Hairdryer: Images.HAIRDRESSER,
  'Direct dial telephone': Images.DIRECT_DIAL,
  'Satellite/cable TV': Images.CABEL_TV,
  Radio: Images.RADIO,
  Kitchenette: Images.KITCHENETTE,
  Minibar: Images.MINIBAR,
  'Air conditioning (centrally regulated)': Images.AC,
  Safe: Images.SAFE,
  'Balcony/Terrace': Images.BALCONY,
  TV: Images.TV,
  'Double Bed': Images.DOUBLE_BED,
  'Air conditioning (individually regulated)': Images.AC,
  'Tea/coffee maker': Images.CAFE,
};

// Default icon if no match is found
export const defaultIcon = Images.DEFAULT_ICON; // Ensure you have a fallback image in your Images config
